name: 'Build and Deploy'
description: 'Build app and deploy to GitHub Pages'
runs:
  using: 'composite'
  steps:
    - name: 📦 Setup Node + PNPM + install deps
      uses: ./.github/actions/setup-node-pnpm-install

    - name: Build
      run: pnpm build
      shell: bash

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
