# Taken from obytes' react native template: https://github.com/obytes/react-native-template-obytes

name: 'Setup  Node + PNPM + Install Dependencies'
description: 'Setup  Node + PNPM + Install Dependencies'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 20.12.0
        cache: 'pnpm'

    - name: 📦 Install Project Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
