on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

name: 'release and deploy'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}

  build:
    runs-on: ubuntu-latest
    needs: [release]
    if: ${{ needs.release.outputs.release-created }}
    environment:
      name: github-pages
      url: ${{ needs.deploy.steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: Build
        run: pnpm build
        shell: bash

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
